/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artifacts/{job_id}/{artifact_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Artifact */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job Route */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["getJob"];
        put?: never;
        post?: never;
        /** Delete Job Route */
        delete: operations["deleteJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job Route */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["getJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Manifest */
        get: operations["getJobManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Job */
        post: operations["resumeJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/audius/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Audius */
        get: operations["searchAudius"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/audius/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audius Track */
        get: operations["getAudiusTrack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Direct Upload */
        post: operations["createDirectUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudiusSearchResponse */
        AudiusSearchResponse: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Provider
             * @constant
             */
            provider: "audius";
            /** Tracks */
            tracks: components["schemas"]["AudiusTrack"][];
        } & {
            [key: string]: unknown;
        };
        /** AudiusSource */
        AudiusSource: {
            /**
             * Provider
             * @constant
             */
            provider: "audius";
            /** Track Id */
            track_id: string;
        };
        /** AudiusTrack */
        AudiusTrack: {
            /**
             * Artist
             * @default
             */
            artist: string;
            /** Artwork Url */
            artwork_url?: string | null;
            /** Can Import */
            can_import: boolean;
            /**
             * Duration Seconds
             * @default 0
             */
            duration_seconds: number;
            /** Genre */
            genre?: string | null;
            /** Id */
            id: string;
            /** Import Reason */
            import_reason: string;
            /** License */
            license?: string | null;
            /** Permalink */
            permalink?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
        } & {
            [key: string]: unknown;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Default Profile */
            default_profile: string;
            /** Evaluation Profile */
            evaluation_profile: string;
            product_contract: components["schemas"]["ProductContract"];
            /** Profiles */
            profiles: {
                [key: string]: components["schemas"]["ProfileMetadata"];
            };
            /** Recommended Profile */
            recommended_profile: string;
            /** Stem Contracts */
            stem_contracts?: {
                [key: string]: components["schemas"]["StemContract"];
            };
        } & {
            [key: string]: unknown;
        };
        /** CreateAudiusJobRequest */
        CreateAudiusJobRequest: {
            /**
             * Profile
             * @default null
             */
            profile: string | null;
            source: components["schemas"]["AudiusSource"];
        };
        /** CreateObjectJobRequest */
        CreateObjectJobRequest: {
            input: components["schemas"]["ObjectJobInput"];
            /**
             * Profile
             * @default null
             */
            profile: string | null;
        };
        /** DirectUploadRequest */
        DirectUploadRequest: {
            /** Content Type */
            content_type?: string | null;
            /** Filename */
            filename: string;
        };
        /** DirectUploadResponse */
        DirectUploadResponse: {
            /** Filename */
            filename: string;
            /** Headers */
            headers?: {
                [key: string]: string;
            };
            /** Max Bytes */
            max_bytes?: number | null;
            /** Method */
            method: string;
            object: components["schemas"]["ObjectReference"];
            /** Url */
            url: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobArtifacts */
        JobArtifacts: {
            /** Analysis */
            analysis?: {
                [key: string]: string;
            };
            /** Broad Stems */
            broad_stems?: {
                [key: string]: string;
            };
            /** Bundles */
            bundles?: {
                [key: string]: string;
            };
            /** Derived Stems */
            derived_stems?: {
                [key: string]: string;
            };
            /** Main Stems */
            main_stems?: {
                [key: string]: string;
            };
            /** Midi */
            midi?: {
                [key: string]: string;
            };
            /** Specialist Substems */
            specialist_substems?: {
                [key: string]: string;
            };
            /** Tempo Locked Wavs */
            tempo_locked_wavs?: {
                [key: string]: string;
            };
        };
        /** JobEventsResponse */
        JobEventsResponse: {
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
            /** Next After */
            next_after: number;
        };
        /** JobResponse */
        JobResponse: {
            artifacts?: components["schemas"]["JobArtifacts"];
            /** Error */
            error?: string | null;
            /** Job Id */
            job_id: string;
            /** Missing Features */
            missing_features?: string[];
            /** Rejected Candidates */
            rejected_candidates?: {
                [key: string]: unknown;
            };
            /** Remote Adapter Reason */
            remote_adapter_reason?: string | null;
            /** Remote Adapter Status */
            remote_adapter_status?: string | null;
            /** Stage */
            stage?: string | null;
            /** Status */
            status: string;
            timings?: components["schemas"]["JobTimings"];
        } & {
            [key: string]: unknown;
        };
        /** JobTimings */
        JobTimings: {
            /** Local Elapsed Seconds */
            local_elapsed_seconds?: number | null;
            /** Local Total Seconds */
            local_total_seconds?: number | null;
            /** Worker Total Seconds */
            worker_total_seconds?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ObjectJobInput */
        ObjectJobInput: {
            /** Filename */
            filename: string;
            object: components["schemas"]["ObjectReference"];
        };
        /** ObjectReference */
        ObjectReference: {
            /** Bucket */
            bucket: string;
            /** Key */
            key: string;
            /** Provider */
            provider: string;
        } & {
            [key: string]: unknown;
        };
        /** ProductContract */
        ProductContract: {
            /** Model Supported Stems */
            model_supported_stems: string[];
            /** Specialist Candidate Stems */
            specialist_candidate_stems: string[];
        } & {
            [key: string]: unknown;
        };
        /** ProfileMetadata */
        ProfileMetadata: {
            /** Label */
            label: string;
            /** Public */
            public: boolean;
            /** Tier */
            tier: string;
        } & {
            [key: string]: unknown;
        };
        /** StemContract */
        StemContract: {
            /** Target Stems */
            target_stems: string[];
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getArtifact: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                artifact_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateObjectJobRequest"] | components["schemas"]["CreateAudiusJobRequest"];
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    profile?: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getJobEvents: {
        parameters: {
            query?: {
                after?: string;
                limit?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getJobManifest: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumeJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    searchAudius: {
        parameters: {
            query?: {
                q?: string;
                limit?: string;
                offset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudiusSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getAudiusTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createDirectUpload: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
